### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [beruanglaut115/skrrttt#1]
### Hi, Ihsan

Ada beberapa kesahalan nih:

1. `section id="section1` bisa dipindah kedalam `<div id="content"` yah:
![image](https://github.com/beruanglaut115/skrrttt/assets/73971391/4dddc435-ac03-42aa-8e0d-cdae3348fbde)

2.  Ada double tag penutup nih, dibaikin yah:
![image](https://github.com/beruanglaut115/skrrttt/assets/73971391/dc957662-3191-429e-b159-f8215c2a266b)

3. Ada juga kesahalan di penutup tag `img` nih:
![image](https://github.com/beruanglaut115/skrrttt/assets/73971391/5b1f7e18-520c-4d32-9c2d-ee92caffe2d1)
seharusnya pake self-closing tag seperti begini yah:
```html
<img src="" alt="" width="" height="" />
```
4. Ada input yang kurang required tuh, yang checkbox untuk i have agree blalbalba

itu saja, bila sudah revisi di upload ulang di repository ini aja lalu komen dibawah yah. Thanks

**Comment by ihsaan15** [comment]
Sudah saya upload ulang kak

**Comment by not-xygen** [comment]
Mantap, submission approved. Good luck belajar CSS nanti!!
